Use as-casts and min functor
nevillegrech/gigahorse-toolchain pull request #22
Opened 2021-08-08 04:05 UTC by b-scholz

The current version of Gigahorse exploited a type bug in the implementation of Souffle 2.0.2 for user-defined functors.  In this version, Souffle did not check the result type of functors at all. 

The proposed changes replace the user-defined functors @cast_to_number and @cast_to_symbol user-defined functors by the type conversion operator `as(argument, type)`.
The type conversion casts the `argument` to the type `type`.

Similar, the user-defined operators @min2 and @max2 are not necessary. Souffle has the operators `min(a1,..,an)` and `max(a1,...,an)`.

2021-08-08 04:09 UTC, b-scholz commented
I forgot to say that this change is necessary for newer versions that include the bug-fix for user-defined functors.

2021-08-09 16:36 UTC, iliastsa requested changes
Some minor items. Also, regarding formatting it's best to stick to `as(v, Type)` instead of `as(v,Type)`

2021-08-09 16:36 UTC, iliastsa commented on clientlib/data_structures.dl
> +  !ArrayIdToStorageIndex(as(storVar,symbol), _),
Should be cast to Value

2021-08-09 16:36 UTC, iliastsa commented on clientlib/data_structures.dl
> +  !ArrayIdToStorageIndex(as(storVar,symbol), _).
Should be cast to Value

2021-08-09 16:36 UTC, iliastsa commented on clientlib/data_structures.dl
> +  !ArrayIdToStorageIndex(as(storVar,symbol), _).
Should be cast to Value

2021-08-09 16:36 UTC, iliastsa commented on clientlib/data_structures.dl
> +LoadGlobalVariable(stmt, as(storVar,symbol), var):-
Should be cast to Value

2021-08-11 13:20 UTC, iliastsa commented
LGTM! I'll run some extra checks, and merge it once they're done.

2021-08-11 13:20 UTC, iliastsa approved these changes

2021-08-22 15:28 UTC, b-scholz commented
Can we merge this PR? The new version of Soufflé is out.

2021-08-22 15:42 UTC, merged